batch_size: 64
clip_epsilon: 0.2
contenous_decay: 0.02
device: cuda
ent_coef: 0.01
env_kwargs: {}
env_name: deep_sea_treasure
gae_lambda: 0.95
gamma: 0.99
hidden_dim: 256
init_weight:
- 0.8
- 0.2
lr: 0.0001
max_grad_norm: 0.5
n_epochs: 5
n_rollouts_per_update: 100
n_updates: 1000
safety_boost_factor: 1.5
safety_distance_threshold: 10.0
save_dir: ppo_results
save_interval: 1000
use_wandb: true
vf_coef: 0.5
wandb_project: moiql-ppo
wandb_run_name: ppo
