deterministic: false
device: cuda
max_episode_steps: null
model_path: final_model.pt
n_episodes: 100
output_dir: simulation_results
render: false
render_fps: 1
train_dir: dst_train/20251026_200603/
training_config: config.yaml
