batch_size: 64
clip_epsilon: 0.1
contenous_decay: 0.02
device: cuda
ent_coef: 0.01
env_kwargs: {}
env_name: mo-highway
gae_lambda: 0.95
gamma: 0.99
hidden_dim: 256
init_weight:
- 0.7
- 0.3
lr: 0.0001
max_grad_norm: 0.5
n_epochs: 5
n_rollouts_per_update: 100
n_updates: 1000
safety_boost_factor: 2.0
safety_distance_threshold: 5.0
save_dir: ppo_results
save_interval: 1000
use_wandb: false
vf_coef: 0.5
wandb_project: moiql-ppo
wandb_run_name: ppo
