action_dim: 4
device: cuda
ekf:
  initial_variance: 10000.0
  observation_noise: 0.1
  process_noise: 0.01
expert_dir: simulation_rl/dst_drift/
gp:
  kernel_type: rbf
  length_scale: 1.0
  observation_noise: 0.1
  signal_variance: 1.0
iql:
  gamma: 0.99
  hidden_dim: 256
  lr: 1.0e-07
  mismatch_coef: 0.0
  n_updates: 20000
  tau: 0.001
  weight_decay: 0.01
n_objectives: 2
n_trajectories: 100
obs_dim: 28
pf:
  n_particles: 1000
  observation_noise: 1.0
  process_noise: 0.05
save_dir: moiql_results
save_step: 1000
ssm_type: pf
use_wandb: false
wandb_project: MOIQL
