# Simulation configuration for trajectory collection
# Model settings
train_dir: "highway_train/20251026_200156/"  # Path to trained model directory
model_path: 'final_model.pt'  # Filename of the trained model
training_config: "config.yaml"  # Path to training config (for environment setup)

# Simulation settings
n_episodes: 100  # Number of episodes to simulate
max_episode_steps: null  # Max timesteps per episode. null means no limit use done signal only
deterministic: false  # Use deterministic policy (argmax) vs stochastic (sampling)
render: false  # Enable pygame rendering to watch episodes (set to true to visualize)
render_fps: 1  # Frames per second when rendering
device: "cuda"  # cuda or cpu

# Output settings
output_dir: "simulation_rl"  # Directory to save trajectory data
