# Simulation configuration for trajectory collection
# Model settings
train_dir: "ppo_results/20251021_012732/"  # Path to trained model directory
model_path: 'final_model.pt'  # Filename of the trained model
training_config: "config.yaml"  # Path to training config (for environment setup)

# Simulation settings
n_episodes: 1000  # Number of episodes to simulate
max_episode_steps: 100  # Max timesteps per episode. null means no limit use done signal only
deterministic: false  # Use deterministic policy (argmax) vs stochastic (sampling)
device: "cuda"  # cuda or cpu

# Output settings
output_dir: "simulation_results"  # Directory to save trajectory data
