action_dim: 4
device: cuda
ekf:
  initial_variance: 10000.0
  observation_noise: 0.1
  process_noise: 0.05
expert_dir: simulation_rl/dst_from_1_decay_1e-2/
gp:
  kernel_type: rbf
  length_scale: 1.0
  observation_noise: 0.1
  signal_variance: 1.0
iql:
  batch_size: 256
  gamma: 0.99
  hidden_dim: 256
  lr: 1.0e-06
  mismatch_coef: 0.0
  n_epochs: 10000
  tau: 0.01
  weight_decay: 0.01
kf:
  initial_variance: 10000.0
  observation_noise: 0.1
  process_noise: 0.05
n_objectives: 2
n_trajectories: 10
obs_dim: 28
pf:
  n_particles: 1000
  observation_noise: 0.1
  process_noise: 0.05
save_dir: moiql_results
ssm_type: kf
use_wandb: false
wandb_project: MOIQL
